import type { Metadata } from "next";
import "./globals.css";
import {Manrope } from "next/font/google";

import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer"

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body  className={`${manrope.className} antialiased  `}>
        <Navbar />
        <div>{children}</div>
        <Footer/>
      </body>
    </html>
  );
}
